#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/vrv
#    username: postgres
#    password: sandeep369
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 414F645367566B596F3373367639793042404529482C4C6351655468576C5A71
#      expiration: 86400000
#      refresh-token:
#        expiration: 604800000


spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

application:
  security:
    jwt:
      secret-key: 414F645367566B596F3373367639793042404529482C4C6351655468576C5A71
      expiration: 86400000
      refresh-token:
        expiration: 604800000
